### ISSUE TITLE
用官源的19.07分支编译不成功

### ISSUE THREAD

**Issue by lllrrr2** [project-openwrt/openwrt-naiveproxy#3]
![image](https://user-images.githubusercontent.com/61368564/93476848-d5db0780-f92c-11ea-8b2b-7be9f7011768.png)
![image](https://user-images.githubusercontent.com/61368564/93476871-dd9aac00-f92c-11ea-9bb6-dfad6e3674ef.png)
![image](https://user-images.githubusercontent.com/61368564/93476886-e2f7f680-f92c-11ea-9c11-71b5b68e59b4.png)
不知道是什么原因。请老大帮分析一下，谢谢

**Comment by ihuaer** [comment]
lean的源码也没编译成功 x86

**Comment by 1715173329** [comment]
掐指一算，钱没加够

要求至少 4G 内存
