### ISSUE TITLE
naiveproxy打包有一些问题

### ISSUE THREAD

**Issue by klzgrad** [project-openwrt/openwrt-naiveproxy#4]
最近有用户跑到上游或者其他地方抱怨编译问题，实际是协调不好造成的。我会根据chromium的变化微调编译系统，openwrt这里的打包属于把我的编译系统复制粘贴了，不能自动跟上变化。

https://github.com/klzgrad/naiveproxy/issues/111 这里提出“原生编译”，我以为原生编译要么是在路由器上编译。

理想情况中应该是：openwrt编译使用EXTRA_FLAGS, OPENWRT_FLAGS以及build.sh和get-clang.sh这四个接口。如果有不满足使用的，应该在上游改好，而不是复制粘贴。

1. 这个应该在上游加上可ccache选项

https://github.com/project-openwrt/openwrt/blob/759b1497ca70e279acc65c70da047f69b7b9e42d/package/ctcgfw/naiveproxy/Makefile#L54-L59

2. 这个应该不要，没用
```
	./tools/import-upstream.sh ; \
```
3. 这个属于把get-clang.sh拆分修改了，应该把修改的部分合到上游
```
	. ./init_env.sh "$(ARCH)" "$(BOARD)" $(CPU_TYPE) $(CPU_SUBTYPE) "$(TOOLCHAIN_DIR)" "$(DL_DIR)"; \
```
4. 应该重用EXTRA_FLAGS ./build.sh
```
	export naive_flags="$$$${naive_flags} $$$${naive_ccache_flags}" ; \
```
5. 我不知道python3为什么可以了。按Arch的用法是要python2保险，需要再验证一下。
```
	export OP_STAGING_DIR="$(STAGING_DIR)" ; \
	mkdir -p out ; \
	./gn/out/gn gen "out/Release" --args="$$$${naive_flags}" --script-executable="$(STAGING_DIR_HOSTPKG)/bin/python3" ; \
```

6. 这个是误解，MaxConnectionsPerProxy只对用户的Chrome有用，放路由器上没用
```
/etc/chromium/policies/managed/proxy.json
```

尤其不应该在我的基础上再打补丁，因为我已经是Chromium的补丁，补丁的补丁就很难弄了，有补丁应该合到上游：

7. 这个是不应该出现的，我现在不知道openwrt有什么特点造成了变化，但应该想另一种办法
https://github.com/project-openwrt/openwrt/blob/openwrt-18.06/package/ctcgfw/naiveproxy/patches/001-build-add-OpenWrt-staging-libraries.patch

8. x86和mips64el是可以有的，应该加到上游。mips和mips64你有没有运行测试过？即使能编译也不能运行的。
https://github.com/project-openwrt/openwrt/blob/openwrt-18.06/package/ctcgfw/naiveproxy/patches/002-build-add-mips-x86-OpenWrt-toolchain-definitions.patch

9. 这个也是不应该出现的，arm64_openwrt上游是可以编译的，这里有什么特点造成了变化
https://github.com/project-openwrt/openwrt/blob/openwrt-18.06/package/ctcgfw/naiveproxy/patches/003-build-drop-useless-deps-simd_asm.patch

10. 你的libnss有没有更新？之所以上游只支持openwrt 19是因为 https://github.com/openwrt/packages/issues/10691 ，这个也造成能编译不能运行。

**Comment by 1715173329** [comment]
首先，非常感谢您的反馈，
同时，也为之前未能准确描述清楚而表示歉意。

有关脚本问题，我会再重新整理，以便于更好地提交至上游。

> 2. 这个应该不要，没用

好的，我将于之后去掉。

> 5. 我不知道python3为什么可以了

以目前情况来看，直接构建时调用的脚本均兼容 Python3，且 Python2 已经在 OpenWrt master 分支中[移除](https://github.com/openwrt/packages/commit/2e48a26b1731c030b7df08eb5427045124cca4db)，故此处直接使用 3 替代之。

> 6. 这个是误解，MaxConnectionsPerProxy只对用户的Chrome有用，放路由器上没用

好的，我将于之后删除该文件。

> 7. 这个是不应该出现的，我现在不知道openwrt有什么特点造成了变化，但应该想另一种办法

使用这个 hack 的原因在于，我在测试时发现仅能指定一个 sysroot 目录，但实际上 OpenWrt 的链接库和头文件等并非是集中在同一文件夹内的。

> 8. x86和mips64el是可以有的，应该加到上游。mips和mips64你有没有运行测试过？即使能编译也不能运行的。

是的，x86 / mips64el 应提交至上游，我设计之初仅为了能够编译，故并未考虑过此问题。
另，确实已经有人回报过 mips 编译出错问题，希望能有更好的方法解决。直接调用 GCC 链接器也似乎不能正常编译。

> 9. 这个也是不应该出现的，arm64_openwrt上游是可以编译的，这里有什么特点造成了变化

根据您的 CI log，是可以正常编译的，但我并不清楚 OpenWrt 的编译流程中出现了什么问题，导致除了 x86_64 外其他架构均出现此报错，因此做了一个 hack 以暂时规避。

> 10. 你们的libnss有没有更新？

该软件包已经与上游同步更新，包括 18.06 分支。

**Comment by 1715173329** [comment]
> openwrt编译使用EXTRA_FLAGS, OPENWRT_FLAGS以及build.sh和get-clang.sh这四个接口
如果有不满足使用的，应该在上游改好，而不是复制粘贴。

为了保持 OpenWrt 编译目录整洁，以及上游脚本整洁，
包括各类参数的传递和判断，很难做到完美搭配，
因此，就目前而言，将其独立出来，才是最好的办法。

ASM 的问题有待考究，接下来的几周内我会研究此问题。
